spring:
  application:
    name: vosung-au-app
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  zipkin:
      base-url: http://192.168.2.210:9411/
  sleuth:
    sampler:
      probability: 0.1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
  main:
    allow-bean-definition-overriding: true
  #国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/vsc_au?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: vosung
    password:
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 47.105.53.119
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册中心地址(暂时为本地地址)
    fetch-registry: true
    registry-fetch-interval-seconds: 8
mybatis:
  type-aliases-package: com.vosung.auapi.client.entity
  mapper-locations: "classpath*:mapper/*.xml"


#请求处理的超时时间
#ribbon:
#  ReadTimeout: 120000
##请求连接的超时时间
#  ConnectTimeout: 30000
#关闭feign的hystrix
feign:
  hystrix:
    enabled: true

#打印sql语句信息(#logback对接logstash的日志配置文件)
logging:
  level:
    com:
      vosung:
        authapp:
          dept:
            mapper: DEBUG
          user:
            mapper: DEBUG
          employee:
            mapper: DEBUG
          org:
            mapper: DEBUG
          permission:
            mapper: DEBUG
          position:
            mapper: DEBUG
          role:
            mapper: DEBUG
          sysdata:
            mapper: DEBUG
