spring:
  application:
    name: vosung-au-app
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  zipkin:
      base-url: http://192.168.2.210:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
  #elasticsearch相关配置
  #es的cluster集群名称可以查看服务器安装的集群名称 使用命令：curl http://192.168.2.161:9200 在power-shell获取到集群名称
  #注意端口为9300  9300 是 Java 客户端的端口,支持集群之间的通信。9200 是支持 Restful HTTP 的接口
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: 192.168.2.12:9300
#      repositories:
#        enabled: true
  main:
    allow-bean-definition-overriding: true
  #国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/vsc_au?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: vosung
    password:
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
server:
  port: 9002
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    serviceUrl:
      defaultZone: http://192.168.2.210:8761/eureka/ #服务注册中心地址(开发环境)
    fetch-registry: true
    registry-fetch-interval-seconds: 8
#如果以来其他项目需要扫描下面，就用[] 里面逗号分隔
mybatis:
  type-aliases-package: com.vosung.auapi.client.entity
  mapper-locations: "classpath*:mapper/*.xml"


#请求处理的超时时间
ribbon:
  ReadTimeout: 120000
#请求连接的超时时间
  ConnectTimeout: 30000

hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#关闭feign的hystrix
feign:
  hystrix:
    enabled: true

#打印sql语句信息 # logging： config: classpath:logback-spring.xml  指定日志输出样式级别，对接logstash
logging:
  level:
    com:
      vosung:
        authapp:
          dept:
            mapper: DEBUG
          user:
            mapper: DEBUG
          employee:
            mapper: DEBUG
          org:
            mapper: DEBUG
          permission:
            mapper: DEBUG
          position:
            mapper: DEBUG
          role:
            mapper: DEBUG
          sysdata:
            mapper: DEBUG
