server:
  port: 9042
spring:
  application:
    name: au-api
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://192.168.2.210:9411/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.210:8761/eureka/ #服务注册中心地址(开发环境)  http://118.190.206.197:8761/eureka/--生产环境
  instance:
    prefer-ip-address: true
feign-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

